#include "tekari/Metadata.h"

#include <sstream>

TEKARI_NAMESPACE_BEGIN

using namespace std;

Metadata::Metadata()
:   mIsPectralData(false)
,   mInPhi(0.0f)
,   mInTheta(0.0f)
,   mSampleName("Untilted")
,   mPointsInFile(-1)
{}

void Metadata::addLine(const string& line)
{
    mRawMetaData.push_back(line);
}

void Metadata::initInfos()
{
    const string* line;

    mIsPectralData = findLineStartingWith("#spectral data generated by") != nullptr;;

    if ((line = findLineStartingWith("#inphi")) != nullptr) {
        sscanf(line->c_str() + 6, "%f", &mInPhi);
    } else if ((line = findLineStartingWith("#phi_in")) != nullptr) {
        sscanf(line->c_str() + 7, "%f", &mInPhi);
    }
    
    if ((line = findLineStartingWith("#intheta")) != nullptr) {
        sscanf(line->c_str() + 8, "%f", &mInTheta);
    } else if ((line = findLineStartingWith("#theta_in")) != nullptr) {
        sscanf(line->c_str() + 9, "%f", &mInTheta);
    }

    if ((line = findLineStartingWith("#datapoints_in_file")) != nullptr) {
        sscanf(line->c_str() + 20, "%d", &mPointsInFile);
    }
    
    if ((line = findLineStartingWith("#sample_name")) != nullptr) {
        mSampleName = stripQuoteMarks(line->substr(13));
    }
}

string Metadata::toString() const
{
    ostringstream result;
    for (const auto& line : mRawMetaData)
        result << line << '\n';
    return result.str();
}

const string* Metadata::findLineContaining(const string &target) const
{
    for (const auto& line : mRawMetaData)
        if (line.find(target) != string::npos)
            return &line;
    return nullptr;
}

const string* Metadata::findLineStartingWith(const string &target) const
{
    for (const auto& line : mRawMetaData)
        if (line.find(target) == 0)
            return &line;
    return nullptr;
}

TEKARI_NAMESPACE_END